.Dd July 16, 2025
.Dt B2CL 1
.Os
.
.Sh NAME
.Nm b2cl
.Nd
.Xr ccl 7
compiler written in itself
.
.Sh SYNOPSIS
.Nm
<
.Ar code
>
.Ar compiled
.
.Sh DESCRIPTION
.Nm
is a compiler of
.Xr ccl 7
that is written in itself.
It should support all language features.
.
.Sh SEE ALSO
.Xr ccl 7 ,
.Xr 3cl 1 interpreter written in C
to bootstrap is available
.Lk https://git.nakidai.ru/3cl here
